const list = [
  {
    id: 1,
    title: "",
    description: "",
    img: "",
    amount: 1,
  },
  {
    id: 2,
    title: "",
    description: "",
    img: "",
    amount: 1,
  },
  {
    id: 3,
    title: "",
    description: "",
    price: 143,
    img: "",
    amount: 1,
  },
  {
    id: 4,
    title: "",
    description: "",
    price: 57,
    img: "",
    amount: 1,
  },
  {
    id: 5,
    title: "Purple Rose Bouquet",
    description: "Sophisticated Beauty in Purple",
    price: 100,
    img: "https://th.bing.com/th/id/OIP.fh1nLE7SR3887s-mws2DxgHaLH?rs=1&pid=ImgDetMain",
    amount: 1,
  },
  {
    id: 6,
    title: "Vine Rose Bouquet",
    description: "Vibrant Red Rose in Bloom",
    price: 135,
    img: "https://www.blueberrystreetflowers.co.uk/wp-content/uploads/2020/07/red-roses-artificial-flowers-scaled.jpg",
    amount: 1,
  },
  {
    id: 7,
    title: "Red & Yellow Rose Bouquet ",
    description: "Radiant Blend of Red and Yellow",
    price: 200,
    img: "https://i.pinimg.com/originals/15/39/26/15392672752ce84025cc73e506385c8f.jpg",
    amount: 1,
  },
  {
    id: 8,
    title: "Light Rose Tulips Bouquet",
    description: "Delicate Pastel Pink Tulip Blooms",
    price: 200,
    img: "https://m.media-amazon.com/images/I/61ErOeiR5cL._AC_SX425_.jpg",
    amount: 1,
  },
  {
    id: 9,
    title: "Rose Lily Pink Bouquet",
    description: "Pink Rose Lilies, Graceful Blooms",
    price: 100,
    img: "https://w0.peakpx.com/wallpaper/962/467/HD-wallpaper-tulip-flower-bouquet-pink.jpg",
    amount: 1,
  },
  {
    id: 10,
    title: "Vine Red Tulips Bouquet",
    description: "Vibrant Red Tulip Bouquet Delights",
    price: 80,
    img: "https://i.pinimg.com/originals/be/76/26/be76260a9d257155386090a9e7f6b3be.jpg",
    amount: 1,
  },
  {
    id: 11,
    title: "Yellow Tulips Bouquet ",
    description: "Sunny Yellow Tulips, Brighten Days",
    price: 120,
    img: "https://i.pinimg.com/originals/a8/ef/b7/a8efb712f7dbf112a13081221840bcdd.jpg",
    amount: 1,
  },
  {
    id: 12,
    title: "Red Tulips Bouquet",
    description: "Bold Red Tulip Bouquet Radiates",
    price: 150,
    img: "https://i.pinimg.com/736x/02/0f/c9/020fc937fbf573c61d83749c31a5cb84.jpg",
    amount: 1,
  },
  {
    id: 13,
    title: "Pinkey White Tulips Bouquet",
    description: "Pretty Pink Tulips, Spring's Charm",
    price: 150,
    img: "https://i.pinimg.com/236x/df/45/81/df45815f3be7a7920311f1c9859407c1.jpg",
    amount: 1,
  },
  {
    id: 14,
    title: "Light Pink Tulips Bouquet",
    description: "Soft Pink Tulip Bouquet Elegance",
    price: 120,
    img: "https://th.bing.com/th/id/OIP.zafmlKnUZPg5v9cP1y9o-QHaNK?w=911&h=1620&rs=1&pid=ImgDetMain",
    amount: 1,
  },
  {
    id: 15,
    title: "Purple Tulips Bouquet",
    description: "Purple Tulips, Royal Garden Delight",
    price: 200,
    img: "https://i.pinimg.com/originals/5e/aa/8c/5eaa8ce00d4016c839a4dd6c0de9a75b.jpg",
    amount: 1,
  },
  {
    id: 16,
    title: "Yellow Rose Bouquet",
    description: "Sunny Yellow Rose Bouquet Cheer",
    price: 100,
    img: "https://th.bing.com/th/id/R.c35d52898f8a6bff28b47c1a662c70a5?rik=pLLC0zRVKJxSnA&riu=http%3a%2f%2fd28xhcgddm1buq.cloudfront.net%2fproduct-images%2frose-bud-flower-gold-24-1.jpg&ehk=lY3ZHFswcMjgxGo8Jps5IodTYbrv%2fDDZPWyQs3w6%2bWM%3d&risl=&pid=ImgRaw&r=0",
    amount: 1,
  },
];

export default list;
